### ISSUE TITLE
list how manny giveawys that is open in playing.

### ISSUE THREAD

**Issue by lukkan99** [iScrE4m/IdiotechDiscordBot#6]
as the titlel says. this culd help with less !giveaway in chat for who wonder if any is open.

**Comment by djetelina** [comment]
Interesting idea, I like having !help there, as that's the most important thing and playing doesn't offer you much space.

Discord has plans to stickied messages however, so we could have a sticky message with that in future. I'll review this issue when discord introduces that feature

**Comment by djetelina** [comment]
When Idiotech gives the bot permission to change topic, he will be changing that.
